name: Lint and Test
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Run ruff check
        run: uv run ruff check
